@startuml
!include style.puml
skinparam ArrowFontStyle plain

box UI UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
participant "commandTextField:TextField" as TextField UI_COLOR
end box

[-> CommandBox : handleKeyPress(event)
activate CommandBox

opt [KeyCode.UP pressed && historyPointer > 0]
    CommandBox -> CommandBox : historyPointer--
    activate CommandBox
    deactivate CommandBox

    CommandBox -> CommandBox : setCommandTextFromHistory()
    activate CommandBox

    CommandBox -> TextField : setText(commandText)
    activate TextField
    TextField --> CommandBox
    deactivate TextField

    CommandBox -> TextField : positionCaret(length)
    activate TextField
    TextField --> CommandBox
    deactivate TextField

    deactivate CommandBox
end

[<-- CommandBox
deactivate CommandBox
@enduml
